# ~/ros2_ws/arducam_params.yaml
/**:
    ros__parameters:
      video_device: "/dev/video0"
      image_width: 1280
      image_height: 720
      pixel_format: "yuyv2rgb" # see usb_cam/supported_formats for list of supported formats 
      #pixel_format: "yuyv2rgb" # see usb_cam/supported_formats for list of supported formats 
      framerate: 30.0
      camera_name: "arducam_8mm" 
#      camera_info_url: "file:///home/bernard/.ros/camera_info/arducam_16mm.yaml" # <--- Direct path
      camera_info_url: "package://usb_cam/config/arducam_8mm_cal.yaml"
#      camera_info_url: "" 
      frame_id: "usb_camera_link"
      io_method: "mmap"

      
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      white_balance_automatic: true
      white_balance: 4000
      auto_exposure: true
      exposure: 50
      autofocus: false
      focus: -1
      
